"""Mock Tests: the sixteen required cases. The additive piece is Qwen verification of
official-PYQ questions over the real UPSC CSE 2026 Essay paper; routing, scoring and attempt
storage are pre-existing TS/app behaviour and are asserted here at the data-invariant level, not
re-implemented. The LLM is stubbed for determinism; the live-model proof is the mock replay.

No question is generated by a model, no engine is changed, and no attempt store is touched.
"""
from __future__ import annotations

import json
import unittest

from .verification.adapters import claim_from_question
from .verification.client import ProviderError, VerificationProvider
from .verification.schemas import InfraStatus, VerificationDecision
from .verification.verifier import verify

# --- real captured OFFICIAL_PYQ: UPSC CSE 2026 Main Essay paper --------------------------
ESSAY_SRC = ('Civil Services (Main) Examination, 2026 — Essay paper (KVMS-G-ESSY). Section A: '
             'Oxymorons reflect the ironies of life. A grateful mind is very beautiful. '
             'A thorn is a changed bud. When two elephants fight, it is the grass that gets '
             'trampled.')
PROV = {'documentTitle': 'Civil Services (Main) Examination, 2026 — Essay paper (KVMS-G-ESSY)',
        'officialUrl': 'https://www.upsc.gov.in/sites/default/files/QP-CSM-26-010926-ESSAY.pdf'}


def essay_q(num=1, prompt='Oxymorons reflect the ironies of life.', year=2026,
            exam_id='exam-upsc-cse-2026'):
    return {'examId': exam_id, 'paperName': 'CSE 2026 Main Paper I: Essay', 'paperYear': year,
            'stage': 'MAINS', 'section': 'Section A', 'questionNumber': num,
            'promptEnglish': prompt, 'marks': 125, 'answerFormat': 'DESCRIPTIVE',
            'officialAnswerKey': None, 'questionType': 'OFFICIAL_PYQ', 'provenance': PROV}


UPSC_CTX = dict(official_name='Civil Services (Main) Examination',
                authority='Union Public Service Commission')


class _Stub(VerificationProvider):
    def __init__(self, payload=None, raises=None):
        self.cfg = {'model': 'stub'}
        self.payload, self.raises = payload, raises

    def is_enabled(self):
        return True

    def health(self):
        return {'enabled': True, 'reachable': True}

    def complete(self, messages, *, max_tokens=320):
        if self.raises:
            raise self.raises
        return self.payload


def _json(decision, ident=True, ev=True, claim=True):
    return json.dumps({'decision': decision, 'identity_supported': ident,
                       'evidence_supported': ev, 'claim_supported': claim, 'reason': 'stub'})


POISON = _Stub(raises=AssertionError('LLM must not be called after a deterministic failure'))


class TestMockVerification(unittest.TestCase):

    def test_1_correct_exam_routing(self):
        # A UPSC PYQ carries and verifies under UPSC identity.
        c = claim_from_question(essay_q(), source_text=ESSAY_SRC, **UPSC_CTX)
        self.assertEqual(c.exam_id, 'exam-upsc-cse-2026')
        v = verify(c, provider=_Stub(_json('SUPPORTED')))
        self.assertTrue(v.deterministic.passed)

    def test_2_wrong_exam_routing_rejected(self):
        c = claim_from_question(essay_q(exam_id='exam-ssc-cgl-2026'), source_text=ESSAY_SRC,
                                official_name='Combined Graduate Level Examination',
                                authority='Staff Selection Commission')
        v = verify(c, provider=POISON)
        self.assertFalse(v.publishable)
        self.assertFalse(v.deterministic.cross_exam_ok)
        self.assertIsNone(v.llm)

    def test_3_correct_stage_and_paper(self):
        c = claim_from_question(essay_q(), source_text=ESSAY_SRC, **UPSC_CTX)
        self.assertIn('mains', c.field)
        self.assertIn('essay', c.field)
        self.assertTrue(c.field.endswith(':q1'))

    def test_4_scoring_descriptive_not_machine_scored(self):
        q = essay_q()
        self.assertEqual(q['marks'], 125)
        self.assertEqual(q['answerFormat'], 'DESCRIPTIVE')
        self.assertIsNone(q['officialAnswerKey'])            # no invented score/key

    def test_5_negative_marking_absent_for_descriptive(self):
        q = essay_q()
        self.assertNotIn('options', q)                       # no MCQ options -> no neg marking
        self.assertIsNone(q['officialAnswerKey'])

    def test_6_unanswered_has_no_key_for_descriptive(self):
        # A descriptive question has no correct option; "unanswered" is not machine-scored.
        self.assertIsNone(essay_q()['officialAnswerKey'])

    def test_7_question_identity(self):
        c = claim_from_question(essay_q(num=5), source_text=ESSAY_SRC, **UPSC_CTX)
        self.assertEqual(c.exam_id, 'exam-upsc-cse-2026')
        self.assertEqual(c.cycle, '2026')
        self.assertTrue(c.field.endswith(':q5'))

    def test_8_cross_exam_isolation(self):
        # SSC evidence can never verify a UPSC question.
        ssc_src = ('Staff Selection Commission — Combined Graduate Level Examination, 2026, '
                   'Tier-I. General Awareness question paper.')
        c = claim_from_question(essay_q(), source_text=ssc_src, **UPSC_CTX)
        v = verify(c, provider=POISON)
        self.assertFalse(v.publishable)
        self.assertFalse(v.deterministic.cross_exam_ok)
        self.assertIsNone(v.llm)

    def test_9_cross_cycle_isolation(self):
        src2025 = ('Civil Services (Main) Examination, 2025 — Essay paper. '
                   'Oxymorons reflect the ironies of life.')
        c = claim_from_question(essay_q(year=2026), source_text=src2025, **UPSC_CTX)
        v = verify(c, provider=POISON)
        self.assertFalse(v.publishable)
        self.assertFalse(v.deterministic.cycle_ok)
        self.assertIsNone(v.llm)

    def test_10_llm_unavailable_never_verified(self):
        c = claim_from_question(essay_q(), source_text=ESSAY_SRC, **UPSC_CTX)
        v = verify(c, provider=_Stub(raises=ProviderError(InfraStatus.LLM_UNAVAILABLE, 'down')))
        self.assertFalse(v.publishable)
        self.assertIs(v.infra, InfraStatus.LLM_UNAVAILABLE)

    def test_11_malformed_llm_never_verified(self):
        c = claim_from_question(essay_q(), source_text=ESSAY_SRC, **UPSC_CTX)
        v = verify(c, provider=_Stub('not json'))
        self.assertFalse(v.publishable)
        self.assertIs(v.infra, InfraStatus.LLM_INVALID_RESPONSE)

    def test_12_invalid_generated_question_not_verifiable_as_official(self):
        # A generated question has no official provenance and no source document -> the span
        # cannot be confirmed -> NEEDS_REVIEW; it can never be verified as an official PYQ.
        gen = {'examId': 'exam-ssc-cgl-2026', 'paperName': 'GovOS drill', 'paperYear': 2026,
               'stage': 'TIER_1', 'questionNumber': 1,
               'promptEnglish': 'A train 120 m long crosses a pole in 6 s. Find its speed.',
               'questionType': 'AI_GENERATED', 'provenance': {}}
        c = claim_from_question(gen, official_name='Combined Graduate Level Examination',
                                authority='Staff Selection Commission')  # no source_text
        v = verify(c, provider=POISON)
        self.assertFalse(v.publishable)
        self.assertIsNone(v.llm)

    def test_13_generated_question_labelled_distinctly(self):
        self.assertEqual(essay_q()['questionType'], 'OFFICIAL_PYQ')
        gen = {'questionType': 'AI_GENERATED'}
        self.assertNotEqual(gen['questionType'], 'OFFICIAL_PYQ')   # never conflated

    def test_14_official_pyq_verifies_as_official(self):
        c = claim_from_question(essay_q(), source_text=ESSAY_SRC, **UPSC_CTX)
        v = verify(c, provider=_Stub(_json('SUPPORTED')))
        self.assertTrue(v.publishable)
        self.assertEqual(v.status, 'VERIFIED')
        self.assertIs(v.llm.decision, VerificationDecision.SUPPORTED)

    def test_15_missing_question_data(self):
        c = claim_from_question(essay_q(prompt=''), source_text=ESSAY_SRC, **UPSC_CTX)
        self.assertFalse(c.requires_value)                   # no prompt -> nothing to verify
        v = verify(c, provider=POISON)
        self.assertFalse(v.publishable)

    def test_16_every_official_question_carries_an_exam_id(self):
        # Attempt-history integrity rests on every question naming its exam; a blank id would
        # let an attempt file against no exam. (The attempt store itself rejects a blank id.)
        for n in range(1, 9):
            self.assertTrue(essay_q(num=n)['examId'])


if __name__ == '__main__':
    unittest.main(verbosity=2)
